name:                intro-to-parsing-stack
version:             0.1.0.0
github:              "https://github.com/SnowOnion/JakeWheat-intro_to_parsing-stack"
# inherited from https://github.com/JakeWheat/intro_to_parsing/blob/master/README.asciidoc
license:             BSD3
# proper to say so?
author:              "Jake Wheat, SnowOnion"
maintainer:          "snowonionlee@gmail.com"
# hmmm BSD3 + copyright = ? && proper to say so?
copyright:           "2018 Jake Wheat, SnowOnion"


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SnowOnion/JakeWheat-intro_to_parsing-stack>

dependencies:
- base >= 4.7 && < 5
# - parsec == 3.1.9
- parsec == 3.1.13.0

library:
  source-dirs: src

executables:
  intro-to-parsing-stack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intro-to-parsing-stack

tests:
  intro-to-parsing-stack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intro-to-parsing-stack
